"""empty message

Revision ID: 1a89693c647f
Revises: c33ab350da56
Create Date: 2020-08-08 20:58:24.665317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a89693c647f'
down_revision = 'c33ab350da56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""UPDATE "Venue" SET genres = CONCAT('{', genres);""")
    op.execute("""UPDATE "Venue" SET genres = CONCAT(genres, '}');""")
    
    op.alter_column('Venue', 'genres',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.ARRAY(sa.String(length=100)),
               existing_nullable=True,
               postgresql_using='genres::character varying(100)[]')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'genres',
               existing_type=sa.ARRAY(sa.String(length=100)),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###
