"""empty message

Revision ID: c33ab350da56
Revises: c6a6f3ced028
Create Date: 2020-08-08 20:43:57.457285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c33ab350da56'
down_revision = 'c6a6f3ced028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""UPDATE "Artist" SET genres = CONCAT('{', genres);""")
    op.execute("""UPDATE "Artist" SET genres = CONCAT(genres, '}');""")

    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.ARRAY(sa.String(length=100)),
               existing_nullable=True,
               postgresql_using='genres::character varying(100)[]')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=sa.ARRAY(sa.String(length=100)),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###
